package br.com.nexo.marcenaria365

import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.view.WindowInsets
import android.widget.*

class NewClientScreen(private val activity: Activity, private val onBack: () -> Unit, private val onSave: (String,String) -> Unit) {
 private val navy=Color.rgb(26,52,67); private val cream=Color.rgb(250,245,239); private val ink=Color.rgb(42,57,66); private val muted=Color.rgb(150,148,143)
 private fun dp(n:Int)=(n*activity.resources.displayMetrics.density+.5f).toInt()
 private fun edit(hint:String)=EditText(activity).apply{this.hint=hint;textSize=14f;setTextColor(ink);setHintTextColor(muted);setSingleLine(true);background=GradientDrawable().apply{setColor(Color.WHITE);cornerRadius=dp(8).toFloat();setStroke(dp(1),0xFFE4DCD4.toInt())};setPadding(dp(14),0,dp(14),0);minimumHeight=dp(54)}
 fun show(){val root=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(cream)};root.setOnApplyWindowInsetsListener{v,i->if(android.os.Build.VERSION.SDK_INT>=30){val x=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom)};i};val h=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),dp(12),dp(16),dp(12));setBackgroundColor(navy)};h.addView(TextView(activity).apply{text="‹";textSize=38f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;setOnClickListener{onBack()}},LinearLayout.LayoutParams(dp(45),dp(48)));h.addView(TextView(activity).apply{text="Novo cliente";textSize=20f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD)},LinearLayout.LayoutParams(0,dp(48),1f));root.addView(h);val c=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(22),dp(25),dp(22),dp(20))};c.addView(TextView(activity).apply{text="Cadastrar cliente";textSize=23f;setTextColor(ink);setTypeface(null,Typeface.BOLD)});c.addView(TextView(activity).apply{text="Informe os dados básicos do seu cliente.";textSize=14f;setTextColor(muted)},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8);bottomMargin=dp(28)});c.addView(TextView(activity).apply{text="Nome completo";textSize=14f;setTextColor(ink);setTypeface(null,Typeface.BOLD)});val name=edit("Digite o nome do cliente");c.addView(name,LinearLayout.LayoutParams(-1,dp(54)).apply{topMargin=dp(8);bottomMargin=dp(20)});c.addView(TextView(activity).apply{text="Telefone";textSize=14f;setTextColor(ink);setTypeface(null,Typeface.BOLD)});val phone=edit("(00) 00000-0000");c.addView(phone,LinearLayout.LayoutParams(-1,dp(54)).apply{topMargin=dp(8);bottomMargin=dp(20)});c.addView(TextView(activity).apply{text="E-mail (opcional)";textSize=14f;setTextColor(ink);setTypeface(null,Typeface.BOLD)});val email=edit("cliente@email.com");c.addView(email,LinearLayout.LayoutParams(-1,dp(54)).apply{topMargin=dp(8)});root.addView(c,LinearLayout.LayoutParams(-1,0,1f));val b=Button(activity).apply{text="Salvar cliente";isAllCaps=false;textSize=16f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD);background=GradientDrawable().apply{setColor(navy);cornerRadius=dp(10).toFloat()};setOnClickListener{if(name.text.isBlank()){name.error="Informe o nome"}else if(phone.text.isBlank()){phone.error="Informe o telefone"}else onSave(name.text.toString().trim(),phone.text.toString().trim()+if(email.text.isNotBlank())" • ${email.text}" else "")}};root.addView(b,LinearLayout.LayoutParams(-1,dp(54)).apply{leftMargin=dp(22);rightMargin=dp(22);bottomMargin=dp(18)});activity.setContentView(root);root.requestApplyInsets()}
}
