package br.com.nexo.marcenaria365

import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.view.WindowInsets
import android.widget.*

private fun fdp(a:Activity,n:Int)=(n*a.resources.displayMetrics.density+.5f).toInt()
private fun fbg(a:Activity,c:Int,r:Int)=GradientDrawable().apply{setColor(c);cornerRadius=fdp(a,r).toFloat();setStroke(fdp(a,1),0xFFE2D9CF.toInt())}

class NewServiceScreen(private val a:Activity,private val store:DemoStore,private val back:()->Unit,private val save:(Job)->Unit){
 fun show(){val r=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(0xFFFAF6F0.toInt())};val h=LinearLayout(a).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(fdp(a,18),0,fdp(a,12),0);setBackgroundColor(0xFF1A3443.toInt())};h.addView(TextView(a).apply{text="‹";textSize=38f;setTextColor(Color.WHITE);setOnClickListener{back()}},LinearLayout.LayoutParams(fdp(a,45),fdp(a,64)));h.addView(TextView(a).apply{text="Novo serviço";textSize=20f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD);gravity=Gravity.CENTER},LinearLayout.LayoutParams(0,fdp(a,64),1f));h.addView(TextView(a).apply{text="⋮";textSize=30f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(fdp(a,30),fdp(a,64)));r.addView(h);val s=ScrollView(a);val c=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setPadding(fdp(a,22),fdp(a,28),fdp(a,22),fdp(a,20))};c.addView(TextView(a).apply{text="▧\nAdicionar foto (opcional)";textSize=15f;gravity=Gravity.CENTER;setTextColor(0xFF999591.toInt());setPadding(0,fdp(a,12),0,fdp(a,38))},LinearLayout.LayoutParams(-1,fdp(a,120)));fun cap(x:String){c.addView(TextView(a).apply{text=x;textSize=13f;setTypeface(null,Typeface.BOLD);setTextColor(0xFF2A3942.toInt())},LinearLayout.LayoutParams(-1,-2).apply{topMargin=fdp(a,12)})};fun field(hint:String,multi:Boolean=false):EditText{val e=EditText(a).apply{this.hint=hint;textSize=14f;setTextColor(0xFF2A3942.toInt());setHintTextColor(0xFF9B9994.toInt());setPadding(fdp(a,12),0,fdp(a,12),0);background=fbg(a,Color.WHITE,7);setSingleLine(!multi);if(multi)gravity=Gravity.TOP;minHeight=fdp(a,if(multi)92 else 52)};c.addView(e,LinearLayout.LayoutParams(-1,fdp(a,if(multi)92 else 52)).apply{topMargin=fdp(a,8)});return e};cap("Cliente");field("Selecione o cliente ⌄");cap("Tipo de serviço");field("Selecione o tipo ⌄");cap("Descrição");val desc=field("Descreva o serviço...",true);cap("Data prevista de entrega");field("DD/MM/AAAA");cap("Valor estimado");field("R$ 0,00");s.addView(c);r.addView(s,LinearLayout.LayoutParams(-1,0,1f));val b=LinearLayout(a).apply{setPadding(fdp(a,22),fdp(a,8),fdp(a,22),fdp(a,18));gravity=Gravity.CENTER_VERTICAL};val cancel=Button(a).apply{text="Cancelar";isAllCaps=false;setTextColor(0xFF2A3942.toInt());background=fbg(a,Color.WHITE,10);setOnClickListener{back()}};val saveb=Button(a).apply{text="Salvar";isAllCaps=false;setTextColor(Color.WHITE);background=fbg(a,0xFFC7C7C5.toInt(),10);setOnClickListener{val cl=store.clients.firstOrNull();if(cl!=null){val j=Job(clientId=cl.id,description=if(desc.text.isBlank())"Novo serviço" else desc.text.toString(),measures="",deadline=null);store.jobs.add(j);save(j)}}};b.addView(cancel,LinearLayout.LayoutParams(0,fdp(a,52),1f));b.addView(saveb,LinearLayout.LayoutParams(0,fdp(a,52),1f).apply{leftMargin=fdp(a,12)});r.addView(b);a.setContentView(r)} }

