package br.com.nexo.marcenaria365
import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.widget.*
class RegisterScreen(private val a:Activity, private val back:()->Unit){
 private val navy=Color.rgb(23,47,63);private val ink=Color.rgb(24,37,49);private val cream=Color.rgb(250,247,242);private fun dp(n:Int)=(n*a.resources.displayMetrics.density).toInt()
 private fun field(h:String)=EditText(a).apply{hint=h;textSize=16f;setTextColor(ink);setHintTextColor(0xFF565858.toInt());setSingleLine(true);setPadding(dp(14),0,dp(14),0);minimumHeight=dp(52);background=GradientDrawable().apply{setColor(Color.WHITE);cornerRadius=dp(8).toFloat();setStroke(dp(1),0xFFDAD2C9.toInt())}}
 fun show(){val root=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(cream)};val head=LinearLayout(a).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(12),0,dp(12),0);setBackgroundColor(navy)};head.addView(TextView(a).apply{text="‹";textSize=38f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;setOnClickListener{back()}},LinearLayout.LayoutParams(dp(48),dp(64)));head.addView(TextView(a).apply{text="Criar conta";textSize=20f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD);gravity=Gravity.CENTER},LinearLayout.LayoutParams(0,dp(64),1f));root.addView(head);val c=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(26),dp(25),dp(26),dp(20))};c.addView(TextView(a).apply{text="Crie sua conta";textSize=24f;setTextColor(ink);setTypeface(null,Typeface.BOLD)});c.addView(TextView(a).apply{text="Preencha seus dados para começar.";textSize=14f;setTextColor(0xFF565858.toInt())},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8);bottomMargin=dp(25)});fun cap(s:String){c.addView(TextView(a).apply{text=s;textSize=13f;setTextColor(ink);setTypeface(null,Typeface.BOLD)},LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(10);bottomMargin=dp(7)})};cap("Nome completo");val n=field("Digite seu nome");c.addView(n);cap("E-mail");val e=field("seu@email.com");c.addView(e);cap("Senha");val p=field("Crie uma senha");p.inputType=129;c.addView(p);cap("Confirmar senha");val cp=field("Digite a senha novamente");cp.inputType=129;c.addView(cp);root.addView(c,LinearLayout.LayoutParams(-1,0,1f));val b=Button(a).apply{text="Criar conta";isAllCaps=false;textSize=16f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD);background=GradientDrawable().apply{setColor(navy);cornerRadius=dp(10).toFloat()};setOnClickListener{if(n.text.isBlank())n.error="Informe o nome" else if(e.text.isBlank())e.error="Informe o e-mail" else if(p.text.toString()!=cp.text.toString())cp.error="As senhas não conferem" else Toast.makeText(a,"Cadastro demonstrativo concluído",Toast.LENGTH_SHORT).show()}};root.addView(b,LinearLayout.LayoutParams(-1,dp(54)).apply{leftMargin=dp(26);rightMargin=dp(26);bottomMargin=dp(18)});a.setContentView(root)} }
