package br.com.nexo.marcenaria365

import android.app.Activity
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.Gravity
import android.view.View
import android.view.WindowInsets
import android.widget.*

class ServiceDetailScreen(private val activity:Activity, private val job:Job, private val client:String, private val back:()->Unit, private val onMovement:()->Unit){
    private val ink=Color.rgb(42,57,66);private val muted=Color.rgb(145,143,138);private val cream=Color.rgb(250,246,240);private val white=Color.rgb(255,253,249);private val navy=Color.rgb(26,52,67);private val tan=Color.rgb(190,145,106);private val green=Color.rgb(38,159,125);private val red=Color.rgb(224,100,102)
    private fun dp(n:Int)=(n*activity.resources.displayMetrics.density+.5f).toInt();private fun bg(c:Int,r:Int)=GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat()};private fun t(s:String,z:Float,c:Int=ink,b:Boolean=false)=TextView(activity).apply{text=s;textSize=z;setTextColor(c);includeFontPadding=false;if(b)setTypeface(null,Typeface.BOLD)}
    fun show(){val root=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(cream)};root.setOnApplyWindowInsetsListener{v,i->if(android.os.Build.VERSION.SDK_INT>=30){val s=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(s.left,s.top,s.right,s.bottom)};i};val head=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),0,dp(12),0);setBackgroundColor(navy)};head.addView(TextView(activity).apply{text="‹";textSize=38f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;setOnClickListener{back()}},LinearLayout.LayoutParams(dp(45),dp(64)));head.addView(t("Detalhes do serviço",20f,Color.WHITE,true),LinearLayout.LayoutParams(0,dp(64),1f));head.addView(t("⋮",30f,Color.WHITE),LinearLayout.LayoutParams(dp(30),dp(64)));root.addView(head)
        val scroll=ScrollView(activity).apply{isFillViewport=true;isVerticalScrollBarEnabled=false};val content=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(20),dp(20),dp(20))};val intro=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL};intro.addView(ImageView(activity).apply{setImageResource(R.drawable.background);scaleType=ImageView.ScaleType.CENTER_CROP;contentDescription="Imagem do serviço"},LinearLayout.LayoutParams(dp(96),dp(92)));intro.addView(LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;addView(t(job.description,21f,b=true));addView(t(client,14f,muted),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(10)});addView(t(if(job.progress==Progress.DONE)"Concluído" else "Em produção",12f,0xFFB47D42.toInt(),true).apply{background=bg(0xFFFFEED2.toInt(),7);setPadding(dp(10),dp(7),dp(10),dp(7))},LinearLayout.LayoutParams(-2,-2).apply{topMargin=dp(9)})},LinearLayout.LayoutParams(0,-2,1f).apply{leftMargin=dp(16)});content.addView(intro)
        val tabs=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(0,dp(18),0,dp(10))};listOf("Detalhes","Orçamento","Histórico").forEachIndexed{i,s->val v=t(s,12f);v.gravity=Gravity.CENTER;v.minimumHeight=dp(38);if(i==0)v.background=bg(0xFFF3E4D4.toInt(),24);tabs.addView(v,LinearLayout.LayoutParams(0,dp(38),1f))};content.addView(tabs)
        val info=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;background=bg(white,13);setPadding(dp(16),dp(16),dp(16),dp(10))};info.addView(t("Informações gerais",17f,b=true));fun row(title:String,value:String){val r=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;setPadding(0,dp(15),0,dp(9))};r.addView(t(title,12f,b=true));r.addView(t(value,14f,muted),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(8)});info.addView(r)};row("Cliente",client);row("Prazo de entrega",job.deadline?.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/uuuu"))?:"15/10/2026");row("Descrição",if(job.measures.isBlank())"Cozinha planejada em MDF amadeirado, com bancada e armários superiores." else job.measures);content.addView(info,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(12)})
        val fin=LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;background=bg(white,13);setPadding(dp(16),dp(16),dp(16),dp(16))};fin.addView(t("Financeiro",17f,b=true));val vals=LinearLayout(activity).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(0,dp(18),0,0)};val total=job.approved?.total?:450000;val rec=job.received.takeIf{it>0}?:300000;val bal=total-rec;listOf(arrayOf("Total",total,ink),arrayOf("Recebido",rec,green),arrayOf("Saldo",bal,red)).forEach{item->val name=item[0] as String;val value=item[1] as Long;val color=item[2] as Int;vals.addView(LinearLayout(activity).apply{orientation=LinearLayout.VERTICAL;addView(t(name,11f,muted));addView(t(String.format("R$ %.2f",value/100.0).replace('.',','),15f,color,true),LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(10)})},LinearLayout.LayoutParams(0,-2,1f))};fin.addView(vals);content.addView(fin,LinearLayout.LayoutParams(-1,-2).apply{topMargin=dp(12)});scroll.addView(content);root.addView(scroll,LinearLayout.LayoutParams(-1,0,1f));val button=Button(activity).apply{text="Registrar movimentação";textSize=15f;isAllCaps=false;setTextColor(Color.WHITE);background=bg(navy,10);setOnClickListener{onMovement()}};root.addView(button,LinearLayout.LayoutParams(-1,dp(52)).apply{leftMargin=dp(20);rightMargin=dp(20);bottomMargin=dp(18)});activity.setContentView(root);root.requestApplyInsets()}
}
